CREATE TABLE EMPLOYEE (
    ID SERIAL NOT NULL PRIMARY KEY,
    NAME CHAR VARYING(100) NOT NULL,
    COUNTRY_NAME CHARACTER VARYING(50) NOT NULL,
    PHONE_NUMBER CHARACTER VARYING(50) NOT NULL,
    EMAIL CHARACTER VARYING(50),
    AGE INT NOT NULL,
    SEX CHARACTER VARYING(20)
);

CREATE TABLE PASSANGER (
    ID SERIAL NOT NULL PRIMARY KEY,
    NAME CHAR VARYING(100) NOT NULL,
    COUNTRY_NAME CHARACTER VARYING(50) NOT NULL,
    PHONE_NUMBER CHARACTER VARYING(50) NOT NULL,
    EMAIL CHARACTER VARYING(50),
    AGE INT NOT NULL,
    SEX CHARACTER VARYING(20)
);

CREATE TABLE AIRPORT (
    ID SERIAL NOT NULL PRIMARY KEY,
    IATA_CODE CHAR VARYING(50),
    CITY CHAR VARYING(20),
    COUNTRY CHAR VARYING(20)
);

CREATE TABLE ROUTE (
    ID SERIAL NOT NULL PRIMARY KEY,
    DISTANCE INT NOT NULL,
    DESTINATION_AIRCRAFT_ID INT NOT NULL,
    ARRIVAL_AIRCRAFT_ID INT NOT NULL,
    FOREIGN KEY(DESTINATION_AIRCRAFT_ID) REFERENCES AIRPORT(ID),
    FOREIGN KEY(ARRIVAL_AIRCRAFT_ID) REFERENCES AIRPORT(ID)
);


CREATE TABLE AIRCRAFT_RECOGNITION(
    ID SERIAL NOT NULL PRIMARY KEY,
    WING_POSITION CHAR VARYING(100) NOT NULL,
    ENGINE_POSITION CHAR VARYING(100) NOT NULL,
    TAIL_CONFIGURATION CHAR VARYING(100) NOT NULL
);

CREATE TABLE TECHNICAL (
    ID SERIAL NOT NULL PRIMARY KEY,
    WING_SPAN FLOAT NOT NULL,
    AIRCRAFT_LENGTH FLOAT NOT NULL,
    AIRCRAFT_HEIGHT FLOAT NOT NULL,
    FUEL_CONSUMPTION FLOAT NOT NULL
);

CREATE TABLE AIRCRAFT (
    ID SERIAL NOT NULL PRIMARY KEY,
    AIRCRAFT_NAME CHARACTER VARYING(30),
    AIRCRAFT_TYPE CHARACTER VARYING(30),
    AIRCRAFT_RECOGNITION_ID INT NOT NULL,
    TECHNICAL_ID INT NOT NULL,
    FOREIGN KEY(AIRCRAFT_RECOGNITION_ID) REFERENCES AIRCRAFT_RECOGNITION(ID),
    FOREIGN KEY(TECHNICAL_ID) REFERENCES TECHNICAL(ID)
);

CREATE TABLE AIRCRAFT_SEAT (
    ID SERIAL NOT NULL PRIMARY KEY,
    PLACE_ID CHAR VARYING(30) NOT NULL,
    PRICE INT NOT NULL,
    TRAVEL_CLASS CHARACTER VARYING(20) NOT NULL,
    AIRCRAFT_ID INT NOT NULL,
    FOREIGN KEY(AIRCRAFT_ID) REFERENCES AIRCRAFT(ID)
);

CREATE TABLE FLIGHT_SCHEDULE(
    ID SERIAL NOT NULL PRIMARY KEY,
    STATUS CHAR VARYING(40),
    ARRIVAL_COST FLOAT,
    DEPARTURE_COST FLOAT,
    ARRIVAL_DATE CHAR VARYING(40),
    DEPARTURE_DATE CHAR VARYING(40),
    AIRCRAFT_ID INT NOT NULL,
    ROUTE_ID INT NOT NULL,
    FOREIGN KEY(AIRCRAFT_ID) REFERENCES AIRCRAFT(ID),
    FOREIGN KEY(ROUTE_ID) REFERENCES ROUTE(ID)
);

CREATE TABLE AIRLINE_TRANSACTION (
    ID SERIAL NOT NULL PRIMARY KEY,
    FLIGHT_SCHEDULE_ID INT NOT NULL,
    PASSANGER_ID INT NOT NULL,
    AIRCRAFT_SEAT_ID INT NOT NULL,
    FOREIGN KEY (FLIGHT_SCHEDULE_ID) REFERENCES FLIGHT_SCHEDULE(ID),
    FOREIGN KEY (PASSANGER_ID) REFERENCES PASSANGER(ID),
    FOREIGN KEY (AIRCRAFT_SEAT_ID) REFERENCES AIRCRAFT_SEAT(ID)
);