CREATE TABLE TIME(
    ID INT NOT NULL,
    DAY VARCHAR(2),
    month varchar(2),
    YEAR varchar(4),
    PRIMARY KEY (ID)
);

CREATE TABLE PASSENGER_AGE(
    ID INT NOT NULL,
    AGE VARCHAR(3),
    PRIMARY KEY (ID)
);

CREATE TABLE COUNTRY(
    ID INT NOT NULL,
    NAME VARCHAR(30),
    PRIMARY KEY (ID)
);

CREATE TABLE GENDER(
    ID INT NOT NULL,
    VALUE VARCHAR(6),
    PRIMARY KEY (ID)
);

CREATE TABLE PASSENGER_NATIONALITY(
    ID INT NOT NULL,
    VALUE VARCHAR(100),
    PRIMARY KEY (ID)
);

CREATE TABLE TICKET(
    ID INT NOT NULL,
    TYPE VARCHAR(10),
    PRIMARY KEY (ID)
);

CREATE TABLE TICKET_SALES(
    ID INT NOT NULL,
    TICKET_PRICE FLOAT,
    AGE_ID INTEGER,
    TICKET_ID INTEGER,
    NATIONALITY_ID INTEGER,
    GENDER_ID INTEGER,
    PRIMARY KEY (ID),
    FOREIGN KEY (AGE_ID) REFERENCES PASSENGER_AGE(ID),
    FOREIGN KEY (TICKET_ID) REFERENCES TICKET(ID),
    FOREIGN KEY (NATIONALITY_ID) REFERENCES COUNTRY(ID),
    FOREIGN KEY (GENDER_ID) REFERENCES GENDER(ID)
);

CREATE TABLE FLGIHT_STATISTICS(
    ID INT NOT NULL,
    LF FLOAT,
    PY FLOAT,
    RASK FLOAT,
    CASK FLOAT,
    TIME_ID INTEGER,
    COUNTRY_ID INTEGER,
    PRIMARY KEY (ID),
    FOREIGN KEY (TIME_ID) REFERENCES TIME(ID),
    FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY(ID)
);

CREATE OR REPLACE PROCEDURE FILL_TICKET_SALES AS 
BEGIN
  FOR X IN (SELECT * FROM TICKET JOIN PASENGER ON PASSENGER.ID = TICKET.PASSENGER_ID)
  LOOP
    
    INSERT INTO TICKET_SALES VALUES (
        X.PRICE, 
        SELECT ID FROM PASSENGER WHERE AGE = X.AGE,
        SELECT ID FROM TICKET WHERE TYPE = X.CLASS,
        SELECT ID FROM PASSENGER_NATIONALITY WHERE VALUE = X.NATIONALITY,
        SELECT ID FROM GENDER WHERE VALUE = X.GENDER
    )
  END LOOP;
END;

CREATE OR REPLACE PROCEDURE FILL_FLIGHT_STATISTICS AS 
BEGIN
  FOR X IN (SELECT * FROM (SELECT * FROM FLIGHT_SCHEDULE S JOIN ROUTE R ON FLIGHT_SCHEDULE.ID = ROUTE.FLIGHT_SCHEDULE_ID) JOIN AIRPORT ON AIRPORT.ROUTE_ID = R.ID)
  LOOP
    
    INSERT INTO FLGIHT_STATISTICS VALUES (
        (SELECT COUNT(*) FROM TICKET WHERE TICKET.FLIGHT_SCHEDULE_ID = X.S.ID) / 850,
        (SELECT AVG(PRICE) FROM TICKET WHERE TICKET.FLIGHT_SCHEDULE_ID = X.S.ID) / X.DISTANCE,
        (SELECT SUM(PRICE) FROM TICKET WHERE TICKET.FLIGHT_SCHEDULE_ID = X.S.ID) / 850 * X.DISTANCE
        SELECT ID FROM PASSENGER WHERE AGE = X.AGE,
        SELECT ID FROM TICKET WHERE TYPE = X.CLASS,
        SELECT ID FROM TIME WHERE DAY = (DEPARTURE_DATE).SUBSTR(0,2) AND MONTH = (DEPARTURE_DATE).SUBSTR(3,2) AND YEAR = (DEPARTURE_DATE).SUBSTR(6,4),
        SELECT ID FROM COUNTRY WHERE NAME = (SELECT COUNTRY FROM AIRPORT WHERE X.DEPARTURE_ID = CONTRY.ID)
    )
  END LOOP;
END;