CREATE TABLE TIME(
    ID INT NOT NULL,
    DAY VARCHAR(2),
    month varchar(2),
    YEAR varchar(4),
    PRIMARY KEY (ID)
);

CREATE TABLE PASSENGER_AGE(
    ID INT NOT NULL,
    AGE VARCHAR(3),
    PRIMARY KEY (ID)
);

CREATE TABLE COUNTRY(
    ID INT NOT NULL,
    NAME VARCHAR(30),
    PRIMARY KEY (ID)
);

CREATE TABLE GENDER(
    ID INT NOT NULL,
    VALUE VARCHAR(6),
    PRIMARY KEY (ID)
);

CREATE TABLE PASSENGER_NATIONALITY(
    ID INT NOT NULL,
    VALUE VARCHAR(100),
    PRIMARY KEY (ID)
);

CREATE TABLE TICKET(
    ID INT NOT NULL,
    TYPE VARCHAR(10),
    PRIMARY KEY (ID)
);

CREATE TABLE TICKET_SALES(
    ID INT NOT NULL,
    TICKET_PRICE FLOAT,
    AGE_ID INTEGER,
    TICKET_ID INTEGER,
    NATIONALITY_ID INTEGER,
    GENDER_ID INTEGER,
    PRIMARY KEY (ID),
    FOREIGN KEY (AGE_ID) REFERENCES PASSENGER_AGE(ID),
    FOREIGN KEY (TICKET_ID) REFERENCES TICKET(ID),
    FOREIGN KEY (NATIONALITY_ID) REFERENCES COUNTRY(ID),
    FOREIGN KEY (GENDER_ID) REFERENCES GENDER(ID)
);

CREATE TABLE FLGIHT_STATISTICS(
    ID INT NOT NULL,
    LF FLOAT,
    PY FLOAT,
    RASK FLOAT,
    CASK FLOAT,
    TIME_ID INTEGER,
    COUNTRY_ID INTEGER,
    PRIMARY KEY (ID),
    FOREIGN KEY (TIME_ID) REFERENCES TIME(ID),
    FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY(ID)
);