SELECT * FROM SA_ROUTES WHERE (DESTINATION_AIRCRAFT_ID = 1 AND ARRIVAL_AIRCRAFT_ID = 28) 
    OR (DESTINATION_AIRCRAFT_ID = 28 AND ARRIVAL_AIRCRAFT_ID = 1);
    
DROP TABLE SA_TEMP_ROUTES;
CREATE TABLE SA_TEMP_ROUTES AS (SELECT * FROM SA_ROUTES);
ALTER TABLE SA_TEMP_ROUTES ADD NEW_ID INTEGER;
ALTER TABLE SA_TEMP_ROUTES ADD NEW_DISTANCE INTEGER;

SELECT * FROM SA_TEMP_ROUTES WHERE (DESTINATION_AIRCRAFT_ID = 1 AND ARRIVAL_AIRCRAFT_ID = 28) 
    OR (DESTINATION_AIRCRAFT_ID = 28 AND ARRIVAL_AIRCRAFT_ID = 1);

EXECUTE AUTOMATE_TO_UPDATE_ROTES;
ALTER TABLE SA_TEMP_ROUTES DROP COLUMN NEW_ID;
ALTER TABLE SA_TEMP_ROUTES DROP COLUMN DISTANCE;
ALTER TABLE SA_TEMP_ROUTES RENAME COLUMN NEW_DISTANCE TO DISTANCE;

SELECT * FROM SA_TEMP_ROUTES; --WHERE (DESTINATION_AIRCRAFT_ID = 32 AND ARRIVAL_AIRCRAFT_ID = 32) OR (DESTINATION_AIRCRAFT_ID = 32 AND ARRIVAL_AIRCRAFT_ID = 32);


