/*
SELECT * FROM SA_2_ORC_TICKET;
DROP TABLE SA_NEW_2_ORC_TICKET;


CREATE TABLE SA_NEW_2_ORC_TICKET AS 
    (SELECT ID, PRICE, TRAVEL_CLASS, (FLIGHT_ID + 2000) AS FLIGHT_SCHEDULE_ID, (PASSENGER_ID + 10000) AS PASSENGER_ID
        FROM SA_2_ORC_TICKET);
        

ALTER TABLE SA_NEW_2_ORC_TICKET ADD PRIMARY KEY (ID);

SELECT * FROM SA_1_TICKET;
SELECT * FROM SA_NEW_2_ORC_TICKET;
SELECT * FROM SA_4_ORC_FLIGHT_SCHEDULE;

CREATE TABLE SA_4_ORC_FLIGHT_SCHEDULE AS (
    SELECT (ID + 2000) AS ID, DEPARTURE_DATE, ARRIVAL_DATE, DEPARTURE_COST, ARRIVAL_COST, TOTAL_FLIGHT_COST, ROUTE_ID
    FROM SA_3_ORC_FLIGHT_SCHEDULE
);

ALTER TABLE SA_4_ORC_FLIGHT_SCHEDULE ADD PRIMARY KEY (ID);
*/

SELECT * FROM SA_NEW_2_ORC_TICKET;
SELECT * FROM SA_4_ORC_FLIGHT_SCHEDULE;
SELECT * FROM SA_1_FLIGHt_SCHEDULE;

SELECT ID, DEPARTURE_DATE, ARRIVAL_DATE, DEPARTURE_COST, ARRIVAL_COST, TOTAL_FLIGHT_COST, ROUTE_ID FROM SA_1_FLIGHT_SCHEDULE;

CREATE TABLE X_SA_FLIGHT_SCHEDULE AS (
    (SELECT ID, DEPARTURE_DATE, ARRIVAL_DATE, DEPARTURE_COST, ARRIVAL_COST, TOTAL_FLIGHT_COST, ROUTE_ID FROM SA_1_FLIGHT_SCHEDULE)
    UNION
    (SELECT ID, DEPARTURE_DATE, ARRIVAL_DATE, DEPARTURE_COST, ARRIVAL_COST, TOTAL_FLIGHT_COST, ROUTE_ID FROM SA_4_ORC_FLIGHT_SCHEDULE)
);

CREATE TABLE X_SA_PASSENGERS AS SELECT * FROM SA_3_PASSENGER;
CREATE TABLE X_SA_AIRPORTS AS SELECT * FROM SA_AIRPORTS;


CREATE TABLE TO_DELETE_XSA_FS AS (SELECT ID FROM (SELECT ID, (to_date(ARRIVAL_DATE, 'YYYY-MM-DD') - to_date(DEPARTURE_DATE, 'YYYY-MM-DD')) AS DIF FROM X_SA_FLIGHT_SCHEDULE) WHERE DIF > 2);
SELECT COUNT(*) FROM SA_FLIGHT_SCHEDULE;
SELECT COUNT(*) FROM TO_DELETE_SA_FS;


SELECT * FROM SA_1_TICKET;

CREATE TABLE X_SA_TICKETS AS (
(SELECT ID, PASSENGER_ID, FLIGHT_SCHEDULE_ID, PRICE, TRAVEL_CLASS FROM SA_1_TICKET)
UNION
(SELECT (ID + 1300000) AS ID, (PASSENGER_ID + 10000) AS PASSENGER_ID, (FLIGHT_ID + 2000) AS FLIGHT_SCHEDULE_ID, PRICE, TRAVEL_CLASS FROM SA_2_ORC_TICKET)
);

SELECT COUNT(*) FROM X_SA_TICKETS;
SELECT COUNT(*) FROM X_SA_TICKETS T JOIN X_SA_PASSENGERS P ON T.PASSENGER_ID = P.ID;


SELECT MIN(DEPARTURE_DATE), MAX(DEPARTURE_DATE), MIN(ARRIVAL_DATE), MAX(ARRIVAL_DATE) FROM X_SA_FLIGHT_SCHEDULE;

EXECUTE DELETE_INVALID_XFS;


