SELECT COUNT(*), MAX(ID) FROM SA_1_PASSENGER;
SELECT COUNT(*), MAX(ID), COUNT(DISTINCT(ID)) FROM SA_1_ORC_PASSENGER;

CREATE TABLE SA_NEW_1_ORC_PASSENGER AS (SELECT (ID+10000) AS ID, AGE, COUNTRY_NAME, GENDER FROM SA_1_ORC_PASSENGER);
CREATE TABLE SA_NEW_1_ORC_TICKET AS (SELECT ID, (PASSENGER_ID + 10000) AS PASSENGER_ID, FLIGHT_ID, TRAVEL_CLASS FROM SA_1_ORC_TICKET);

CREATE TABLE SA_2_PASSENGER AS (
    SELECT ID, AGE, UPPER(GENDER) AS GENDER, UPPER(COUNTRY_NAME) AS COUNTRY FROM SA_1_PASSENGER 
    UNION
    SELECT ID, AGE, UPPER(GENDER) AS GENDER, UPPER(COUNTRY_NAME) AS COUNTRY FROM SA_NEW_1_ORC_PASSENGER
);