SELECT * FROM TO_DELETE_XSA_FS;
SELECT COUNT(*) FROM X_SA_FLIGHT_SCHEDULE XSFS JOIN TO_DELETE_XSA_FS TDXFS ON XSFS.ID = TDXFS.ID;
SELECT COUNT(*) FROM X_SA_FLIGHT_SCHEDULE;


CREATE TABLE X2_SA_FLIGHT_SCHEDULE AS (
SELECT ID, DEPARTURE_DATE, ARRIVAL_DATE, DEPARTURE_COST, ARRIVAL_COST, TOTAL_FLIGHT_COST, ROUTE_ID FROM X_SA_FLIGHT_SCHEDULE 
WHERE ID NOT IN (SELECT ID FROM TO_DELETE_XSA_FS));

SELECT MIN(DEPARTURE_DATE), MAX(DEPARTURE_DATE), MIN(ARRIVAL_DATE), MAX(ARRIVAL_DATE) FROM X2_SA_FLIGHT_SCHEDULE;
DROP TABLE X_SA_FLIGHT_SCHEDULE;
CREATE TABLE X_SA_FLIGHT_SCHEDULE AS SELECT * FROM X2_SA_FLIGHT_SCHEDULE;