DROP TABLE SA_ROUTES_CLEARED;
CREATE TABLE SA_ROUTES_CLEARED AS (SELECT * FROM SA_ROUTES);
ALTER TABLE SA_ROUTES_CLEARED ADD NEW_ID INTEGER;
ALTER TABLE SA_ROUTES_CLEARED ADD NEW_DISTANCE INTEGER;


ALTER TABLE SA_ROUTES_CLEARED DROP COLUMN NEW_ID;
ALTER TABLE SA_ROUTES_CLEARED DROP COLUMN DISTANCE;
ALTER TABLE SA_ROUTES_CLEARED RENAME COLUMN NEW_DISTANCE TO DISTANCE;
EXECUTE AUTOMATE_TO_UPDATE_ROTES;

SELECT * FROM SA_ROUTES_CLEARED; --WHERE (DESTINATION_AIRCRAFT_ID = 32 AND ARRIVAL_AIRCRAFT_ID = 32) OR (DESTINATION_AIRCRAFT_ID = 32 AND ARRIVAL_AIRCRAFT_ID = 32);
SELECT * FROM SA_ROUTES;

SELECT COUNT(DISTINCT(ID)) AS SR FROM SA_ROUTES;
SELECT COUNT(DISTINCT(ROUTE_ID)) AS SFS FROM SA_1_FLIGHT_SCHEDULE;
SELECT COUNT(DISTINCT(ID)) AS O_SRC, COUNT(DISTINCT(NEW_ID)) AS N_SRC FROM SA_ROUTES_CLEARED;

SELECT * FROM SA_ROUTES_CLEARED;
SELECT * FROM SA_1_FLIGHT_SCHEDULE;

EXECUTE AUTOMATE_FS_CLEAR_POSTGRES;


