--SELECT * FROM X_SA_AIRPORTS;
--SELECT * FROM X_SA_ROUTES WHERE (DEPARTURE_AIRPORT_ID = 2 AND ARRIVAL_AIRPORT_ID = 16) OR (DEPARTURE_AIRPORT_ID = 16 AND ARRIVAL_AIRPORT_ID = 2) ;
--SELECT * FROM X_SA_FLIGHT_SCHEDULE;
--SELECT * FROM X_SA_TICKETS;
--SELECT * FROM X_SA_PASSENGERS;

DROP TABLE A_SA_MSQL_FLIGHT_DETAILS;
CREATE TABLE A_SA_MSQL_FLIGHT_DETAILS (
    ID INTEGER,
    DEPARTURE_DATE VARCHAR(11),
    ARRIVAL_DATE VARCHAR(11),
    ROUTE_ID INTEGER,
    AIRPLANE_ID INTEGER,
    ARRIVAL_COST INTEGER,
    DEPARTURE_COST INTEGER,
    TOTAL_FUEL_COST INTEGER
)
ORGANIZATION EXTERNAL (  
    TYPE ORACLE_LOADER    
    DEFAULT DIRECTORY imp_danych
    ACCESS PARAMETERS (       
        RECORDS DELIMITED BY NEWLINE
        BADFILE 'sa_route.bad'  
        NODISCARDFILE
        LOGFILE 'sa_route.log' 
        FIELDS TERMINATED BY ',' 
        OPTIONALLY ENCLOSED BY '"' 
        MISSING FIELD VALUES ARE NULL    
        REJECT ROWS WITH ALL NULL FIELDS        
        (
            ID,
            DEPARTURE_DATE,
            ARRIVAL_DATE,
            ROUTE_ID,
            AIRPLANE_ID,
            ARRIVAL_COST,
            DEPARTURE_COST,
            TOTAL_FUEL_COST
        )
    )
    LOCATION ('sa_flight_schedule.csv')
)
REJECT LIMIT Unlimited
NOPARALLEL;

DROP TABLE A_SA_MSQL_PASSENGER;
CREATE TABLE A_SA_MSQL_PASSENGER (
    ID INTEGER,
    AGE INTEGER,
    GENDER VARCHAR(10),
    NATIONALITY VARCHAR(60)
)
ORGANIZATION EXTERNAL (  
    TYPE ORACLE_LOADER    
    DEFAULT DIRECTORY imp_danych
    ACCESS PARAMETERS (       
        RECORDS DELIMITED BY NEWLINE
        BADFILE 'sa_route.bad'  
        NODISCARDFILE
        LOGFILE 'sa_route.log' 
        FIELDS TERMINATED BY ',' 
        OPTIONALLY ENCLOSED BY '"' 
        MISSING FIELD VALUES ARE NULL    
        REJECT ROWS WITH ALL NULL FIELDS        
        (
            ID,
            AGE,
            GENDER,
            NATIONALITY
        )
    )
    LOCATION ('sa_passenger.csv')
)
REJECT LIMIT Unlimited
NOPARALLEL;

DROP TABLE A_SA_MSQL_TICKET;
CREATE TABLE A_SA_MSQL_TICKET (
    ID INTEGER,
    PRICE INTEGER,
    TRAVEL_CLASS VARCHAR(10),
    PASSENGER_ID INTEGER,
    FLIGHT_SCHEDULE_ID INTEGER
)
ORGANIZATION EXTERNAL (  
    TYPE ORACLE_LOADER    
    DEFAULT DIRECTORY imp_danych
    ACCESS PARAMETERS (       
        RECORDS DELIMITED BY NEWLINE
        BADFILE 'sa_route.bad'  
        NODISCARDFILE
        LOGFILE 'sa_route.log' 
        FIELDS TERMINATED BY ',' 
        OPTIONALLY ENCLOSED BY '"' 
        MISSING FIELD VALUES ARE NULL    
        REJECT ROWS WITH ALL NULL FIELDS        
        (
            ID,
            PRICE,
            TRAVEL_CLASS,
            PASSENGER_ID,
            FLIGHT_SCHEDULE_ID
        )
    )
    LOCATION ('sa_ticket.csv')
)
REJECT LIMIT Unlimited
NOPARALLEL;