CREATE TABLE SA_PASSENGER (
    ID NUMBER PRIMARY KEY,
    AGE INTEGER,
    GENDER VARCHAR(7),
    NATIONALITY VARCHAR(40)
);

CREATE TABLE SA_TICKET (
 ID NUMBER PRIMARY KEY,
 PRICE INTEGER,
 TICKET_CLASS VARCHAR(10),
 FLIGH_SCHEDULE_ID INTEGER
);

CREATE TABLE SA_FLIGHT_SCHEDULE (
    ID NUMBER PRIMARY KEY,
    DEPARTURE_DATE DATE,
    ARRIVAL_DATE DATE,
    ROUTE_ID INTEGER,
    AIRCRAFT_ID INTEGER,
    ARRIVAL_COST INTEGER,
    DEPARTURE_COST INTEGER,
    TOTAL_FUEL_COST INTEGER
);

CREATE TABLE SA_AIRPORT (
    ID NUMBER PRIMARY KEY,
    IATA_CODE VARCHAR(3),
    CITY VARCHAR(40),
    COUNTRY VARCHAR(60)
);

CREATE TABLE SA_ROUTE (
    ID NUMBER PRIMARY KEY,
    DEPARTURE_ID INTEGER,
    ARRIVAL_ID INTEGER,
    DISTANCE INTEGER
);