DROP TABLE SA_ORC_FLIGHT_DETAILS;
CREATE TABLE SA_ORC_FLIGHT_DETAILS (
    ID INTEGER,
    AIRPLANEID INTEGER,
    DEPARTURE_TIME VARCHAR(60),
    temp1 INTEGER,
    ARRIVAL_TIME VARCHAR(60),
    temp2 INTEGER,
    DEPARTURE_CODE INTEGER,
    DESTINATION_CODE INTEGER,
    FLIGHT_COST INTEGER,
    DEPARTURE_AIRPORT_COST INTEGER,
    ARRIVALS_AIRPORT_COST INTEGER,
    TOTAL_FREE_BUS_SEATS INTEGER,
    TOTAL_FREE_ECO_SEATS INTEGER,
    WORKERS_COST INTEGER,
    DISTANCE INTEGER
)
ORGANIZATION EXTERNAL (  
    TYPE ORACLE_LOADER    
    DEFAULT DIRECTORY imp_danych
    ACCESS PARAMETERS (       
        RECORDS DELIMITED BY NEWLINE
        BADFILE 'sa_route.bad'  
        NODISCARDFILE
        LOGFILE 'sa_route.log' 
        FIELDS TERMINATED BY ',' 
        OPTIONALLY ENCLOSED BY '"' 
        MISSING FIELD VALUES ARE NULL    
        REJECT ROWS WITH ALL NULL FIELDS        
        (
            ID,
            AIRPLANEID,
            DEPARTURE_TIME,
            temp1,
            ARRIVAL_TIME,
            temp2,
            DEPARTURE_CODE,
            DESTINATION_CODE,
            FLIGHT_COST,
            DEPARTURE_AIRPORT_COST,
            ARRIVALS_AIRPORT_COST,
            TOTAL_FREE_BUS_SEATS,
            TOTAL_FREE_ECO_SEATS,
            WORKERS_COST,
            DISTANCE
        )
    )
    LOCATION ('flight_details.csv')
)
REJECT LIMIT Unlimited
NOPARALLEL;

EXECUTE AUTOMATE_TO_UPDATE_ROTES;

SELECT * FROM SA_1_ORC_FLIGHT_SCHEDULE;

CREATE TABLE SA_1_ORC_FLIGHT_SCHEDULE AS (
    SELECT ID, 
        TO_CHAR(to_date(DEPARTURE_TIME,'DD/MM/YY HH24:MI:SS'), 'RRRR-MM-DD') AS DEPARTURE_DATE,
        TO_CHAR(to_date(ARRIVAL_TIME,'DD/MM/YY HH24:MI:SS'), 'RRRR-MM-DD') AS ARRIVAL_DATE,
        DEPARTURE_CODE,
        DESTINATION_CODE,
        DEPARTURE_AIRPORT_COST AS DEPARTURE_COST,
        ARRIVALS_AIRPORT_COST AS ARRIVAL_COST,
        (FLIGHT_COST + WORKERS_COST) AS TOTAL_FLIGHT_COST
    FROM TEMP_ORC_FS
   );

ALTER TABLE SA_1_ORC_FLIGHT_SCHEDULE 
DROP COLUMN ROUTE_ID ;
        
ALTER TABLE SA_ROUTES_CLEARED RENAME COLUMN DESTINATION_AIRCRAFT_ID TO DEPARTURE_AIRPORT_ID;
ALTER TABLE SA_ROUTES_CLEARED RENAME COLUMN ARRIVAL_AIRCRAFT_ID TO ARRIVAL_AIRPORT_ID;

SELECT ID, DEPARTURE_CODE, DESTINATION_CODE, ROUTE_ID FROM SA_1_ORC_FLIGHT_SCHEDULE;

SELECT SRC.*, SOFS.* FROM SA_ROUTES_CLEARED SRC JOIN SA_1_ORC_FLIGHT_SCHEDULE SOFS 
ON SOFS.DEPARTURE_CODE = SRC.DEPARTURE_AIRPORT_ID AND SRC.ARRIVAL_AIRPORT_ID = SOFS.DESTINATION_CODE;

-- EXECUTE UPDATE_ROUTES;
        
ALTER TABLE SA_2_TEMP_ORC_FLIGHT_SCHEDULE ADD TOTAL_FLIGHT_COST INTEGER;
SELECT * FROM TEMP;
SELECT * FROM SA_1_ORC_FLIGHT_SCHEDULE;

SELECT ID, (FLIGHT_COST + WORKERS_COST) AS SUMA FROM SA_1_ORC_FLIGHT_SCHEDULE;
SELECT SOFS.*, TEMP.ID AS ROUTE_ID FROM TEMP JOIN SA_1_ORC_FLIGHT_SCHEDULE SOFS ON TEMP.DETAILS_ID = SOFS.ID;
CREATE TABLE SA_3_ORC_FLIGHT_SCHEDULE AS (SELECT SOFS.*, TEMP.ID AS ROUTE_ID FROM TEMP JOIN SA_1_ORC_FLIGHT_SCHEDULE SOFS ON TEMP.DETAILS_ID = SOFS.ID);
SELECT * FROM TEMP;

DROP TABLE TEMP;
CREATE TABLE TEMP AS (
SELECT ID, DETAILS_ID FROM (
        SELECT STR.ID, SOFD_DETAILS.ID AS DETAILS_ID, STR.DISTANCE AS DISTANCE, SOFD_DETAILS.DEPARTURE_CODE, SOFD_DETAILS.DESTINATION_CODE FROM SA_ROUTES_CLEARED STR 
            JOIN (
                SELECT ID, DEPARTURE_CODE, DESTINATION_CODE FROM SA_1_ORC_FLIGHT_SCHEDULE) SOFD_DETAILS
            ON SOFD_DETAILS.DEPARTURE_CODE = STR.DEPARTURE_AIRPORT_ID AND 
               SOFD_DETAILS.DESTINATION_CODE = STR.ARRIVAL_AIRPORT_ID)
);
        