CREATE TABLE SA_ORC_GENDER (
    ID INTEGER,
    NAME VARCHAR(10)
) ORGANIZATION EXTERNAL (  
    TYPE ORACLE_LOADER    
    DEFAULT DIRECTORY imp_danych
    ACCESS PARAMETERS (       
        RECORDS DELIMITED BY NEWLINE
        BADFILE 'sa_route.bad'  
        NODISCARDFILE
        LOGFILE 'sa_route.log' 
        FIELDS TERMINATED BY ',' 
        OPTIONALLY ENCLOSED BY '"' 
        MISSING FIELD VALUES ARE NULL    
        REJECT ROWS WITH ALL NULL FIELDS        
        (
            ID, 
            NAME
        )
    )
    LOCATION ('gender.csv')
)
REJECT LIMIT Unlimited
NOPARALLEL;

CREATE TABLE SA_ORC_PASSENGER (
    ID INTEGER,
    AGE INTEGER,
    WEIGHT INTEGER,
    ID_NUMBER VARCHAR(40),
    GENDER INTEGER,
    NATIONALITY VARCHAR(60)
) ORGANIZATION EXTERNAL (  
    TYPE ORACLE_LOADER    
    DEFAULT DIRECTORY imp_danych
    ACCESS PARAMETERS (       
        RECORDS DELIMITED BY NEWLINE
        BADFILE 'sa_route.bad'  
        NODISCARDFILE
        LOGFILE 'sa_route.log' 
        FIELDS TERMINATED BY ',' 
        OPTIONALLY ENCLOSED BY '"' 
        MISSING FIELD VALUES ARE NULL    
        REJECT ROWS WITH ALL NULL FIELDS        
        ( ID, AGE, WEIGHT, ID_NUMBER, GENDER, NATIONALITY )
    )
    LOCATION ('passangers.csv')
)
REJECT LIMIT Unlimited
NOPARALLEL;

CREATE TABLE SA_1_ORC_PASSENGER AS (
    SELECT SOP.ID, SOP.AGE, SOP.NATIONALITY AS COUNTRY_NAME, SOG.NAME AS GENDER 
    FROM SA_ORC_PASSENGER SOP 
    JOIN SA_ORC_GENDER SOG ON SOG.ID = SOP.GENDER
)

