DROP TABLE SA_ORC_FLIGHT_DETAILS;
CREATE TABLE SA_ORC_FLIGHT_DETAILS (
    ID INTEGER,
    AIRPLANEID INTEGER,
    DEPARTURE_TIME VARCHAR(60),
    temp1 INTEGER,
    ARRIVAL_TIME VARCHAR(60),
    temp2 INTEGER,
    DEPARTURE_CODE INTEGER,
    DESTINATION_CODE INTEGER,
    FLIGHT_COST INTEGER,
    DEPARTURE_AIRPORT_COST INTEGER,
    ARRIVALS_AIRPORT_COST INTEGER,
    TOTAL_FREE_BUS_SEATS INTEGER,
    TOTAL_FREE_ECO_SEATS INTEGER,
    WORKERS_COST INTEGER,
    DISTANCE INTEGER
)
ORGANIZATION EXTERNAL (  
    TYPE ORACLE_LOADER    
    DEFAULT DIRECTORY imp_danych
    ACCESS PARAMETERS (       
        RECORDS DELIMITED BY NEWLINE
        BADFILE 'sa_route.bad'  
        NODISCARDFILE
        LOGFILE 'sa_route.log' 
        FIELDS TERMINATED BY ',' 
        OPTIONALLY ENCLOSED BY '"' 
        MISSING FIELD VALUES ARE NULL    
        REJECT ROWS WITH ALL NULL FIELDS        
        (
            ID,
            AIRPLANEID,
            DEPARTURE_TIME,
            temp1,
            ARRIVAL_TIME,
            temp2,
            DEPARTURE_CODE,
            DESTINATION_CODE,
            FLIGHT_COST,
            DEPARTURE_AIRPORT_COST,
            ARRIVALS_AIRPORT_COST,
            TOTAL_FREE_BUS_SEATS,
            TOTAL_FREE_ECO_SEATS,
            WORKERS_COST,
            DISTANCE
        )
    )
    LOCATION ('flight_details.csv')
)
REJECT LIMIT Unlimited
NOPARALLEL;


-- TO_CHAR(to_date(DEPARTURE_DATE,'DD/MM/YYYY HH24:MI:SS'), 'YYYY-MM-DD') AS DEPARTURE_DATE,
-- TO_CHAR(to_date(ARRIVAL_DATE,'DD/MM/YYYY HH24:MI:SS'), 'YYYY-MM-DD') AS ARRIVAL_DATE,
    
-- (SELECT ID FROM SA_ROUTES SR WHERE SR.DESTINATION_AIRCRAFT_ID = SOFD.DEPARTURE_CODE AND SR.ARRIVAL_AIRCRAFT_ID = SOFD.DESTINATION_CODE) AS ROUTE_ID, 
-- SUM(WORKERS_COST, FLIGHT_COST) AS TOTAL_FUEL_COST
DROP TABLE SA_1_ORC_FLIGHT_SCHEDULE;
 CREATE TABLE SA_1_ORC_FLIGHT_SCHEDULE AS (SELECT
    ID,
    DEPARTURE_AIRPORT_COST,
    ARRIVALS_AIRPORT_COST
 FROM SA_ORC_FLIGHT_DETAILS SOFD);

ALTER TABLE SA_1_ORC_FLIGHT_SCHEDULE 
ADD ROUTE_ID INTEGER;
        
CREATE TABLE TEMP AS (
SELECT ID, DETAILS_ID FROM (
        SELECT STR.ID, SOFD_DETAILS.ID AS DETAILS_ID, STR.NEW_DISTANCE AS DISTANCE, SOFD_DETAILS.DEPARTURE_CODE, SOFD_DETAILS.DESTINATION_CODE FROM SA_TEMP_ROUTES STR 
            JOIN (
                SELECT ID, DEPARTURE_CODE, DESTINATION_CODE FROM SA_ORC_FLIGHT_DETAILS) SOFD_DETAILS
            ON SOFD_DETAILS.DEPARTURE_CODE = STR.DESTINATION_AIRCRAFT_ID AND 
               SOFD_DETAILS.DESTINATION_CODE = STR.ARRIVAL_AIRCRAFT_ID) 
);

-- EXECUTE UPDATE_ROUTES;
        
SELECT * FROM TEMP;
SELECT * FROM SA_1_ORC_FLIGHT_SCHEDULE;

        
CREATE TABLE SA_2_ORC_FLIGHT_SCHEDULE AS (SELECT SOFS.*, TEMP.ID AS ROUTE_ID FROM TEMP JOIN SA_1_ORC_FLIGHT_SCHEDULE SOFS ON TEMP.DETAILS_ID = SOFS.ID);

        