DROP TABLE SA_ORC_FLIGHT_DETAILS;
CREATE TABLE SA_ORC_FLIGHT_DETAILS (
    ID INTEGER,
    AIRPLANEID INTEGER,
    DEPARTURE_TIME VARCHAR(60),
    temp1 INTEGER,
    ARRIVAL_TIME VARCHAR(60),
    temp2 INTEGER,
    DEPARTURE_CODE INTEGER,
    DESTINATION_CODE INTEGER,
    FLIGHT_COST INTEGER,
    DEPARTURE_AIRPORT_COST INTEGER,
    ARRIVALS_AIRPORT_COST INTEGER,
    TOTAL_FREE_BUS_SEATS INTEGER,
    TOTAL_FREE_ECO_SEATS INTEGER,
    WORKERS_COST INTEGER,
    DISTANCE INTEGER
)
ORGANIZATION EXTERNAL (  
    TYPE ORACLE_LOADER    
    DEFAULT DIRECTORY imp_danych
    ACCESS PARAMETERS (       
        RECORDS DELIMITED BY NEWLINE
        BADFILE 'sa_route.bad'  
        NODISCARDFILE
        LOGFILE 'sa_route.log' 
        FIELDS TERMINATED BY ',' 
        OPTIONALLY ENCLOSED BY '"' 
        MISSING FIELD VALUES ARE NULL    
        REJECT ROWS WITH ALL NULL FIELDS        
        (
            ID,
            AIRPLANEID,
            DEPARTURE_TIME,
            temp1,
            ARRIVAL_TIME,
            temp2,
            DEPARTURE_CODE,
            DESTINATION_CODE,
            FLIGHT_COST,
            DEPARTURE_AIRPORT_COST,
            ARRIVALS_AIRPORT_COST,
            TOTAL_FREE_BUS_SEATS,
            TOTAL_FREE_ECO_SEATS,
            WORKERS_COST,
            DISTANCE
        )
    )
    LOCATION ('flight_details.csv')
)
REJECT LIMIT Unlimited
NOPARALLEL;


-- TO_CHAR(to_date(DEPARTURE_DATE,'DD/MM/YYYY HH:MM:SS'), 'YYYY-MM-DD') AS DEPARTURE_DATE,
-- TO_CHAR(to_date(ARRIVAL_DATE,'DD/MM/YYYY HH:MM:SS'), 'YYYY-MM-DD') AS ARRIVAL_DATE,
    
-- (SELECT ID FROM SA_ROUTES SR WHERE SR.DESTINATION_AIRCRAFT_ID = SOFD.DEPARTURE_CODE AND SR.ARRIVAL_AIRCRAFT_ID = SOFD.DESTINATION_CODE) AS ROUTE_ID, 
-- SUM(WORKERS_COST, FLIGHT_COST) AS TOTAL_FUEL_COST

-- CREATE TABLE SA_1_ORC_FLIGHT_SCHEDULE AS (SELECT
--    ID,
--    DEPARTURE_AIRPORT_COST,
--    ARRIVALS_AIRPORT_COST
-- FROM SA_ORC_FLIGHT_DETAILS SOFD);

SELECT * FROM SA_ROUTES;
SELECT * FROM SA_1_ORC_FLIGHT_SCHEDULE;
SELECT * FROM SA_ORC_FLIGHT_DETAILS;


SELECT DISTINCT(ID) FROM 
    (SELECT * FROM SA_ROUTES SR 
         JOIN 
            (SELECT DESTINATION_CODE, DEPARTURE_CODE FROM SA_ORC_FLIGHT_DETAILS) SRFD  
        ON DESTINATION_AIRCRAFT_ID = DEPARTURE_CODE AND ARRIVAL_AIRCRAFT_ID = DESTINATION_CODE)
WHERE (DESTINATION_AIRCRAFT_ID = 1 AND ARRIVAL_AIRCRAFT_ID = 28) 
    OR (DESTINATION_AIRCRAFT_ID = 28 AND ARRIVAL_AIRCRAFT_ID = 1);
    
SELECT * FROM SA_ROUTES WHERE (DESTINATION_AIRCRAFT_ID = 1 AND ARRIVAL_AIRCRAFT_ID = 28) 
    OR (DESTINATION_AIRCRAFT_ID = 28 AND ARRIVAL_AIRCRAFT_ID = 1);


ALTER TABLE SA_1_ORC_FLIGHT_SCHEDULE 
ADD ROUTE_ID INTEGER;

UPDATE SA_1_ORC_FLIGHT_SCHEDULE SOFS
    SET ROUTE_ID = (
    SELECT SR.ID 
        FROM SA_ROUTES SR 
            CROSS JOIN SA_ORC_FLIGHT_DETAILS SOFD 
        WHERE SR.DESTINATION_AIRCRAFT_ID = SOFD.DEPARTURE_CODE 
            AND SR.ARRIVAL_AIRCRAFT_ID = SOFD.DESTINATION_CODE)
WHERE SOFS.ID = SOFD.ID;