DROP TABLE SA_ORC_TICKET_IMP;
CREATE TABLE SA_ORC_TICKET_IMP (
    ID INTEGER,
    PASSANGERID INTEGER,
    FLIGHTID INTEGER,
    PLACE VARCHAR(20),
    FLIGHT_NUMBER VARCHAR(20),
    PRICE INTEGER
)
ORGANIZATION EXTERNAL (  
    TYPE ORACLE_LOADER    
    DEFAULT DIRECTORY imp_danych
    ACCESS PARAMETERS (       
        RECORDS DELIMITED BY NEWLINE
        BADFILE 'sa_route.bad'  
        NODISCARDFILE
        LOGFILE 'sa_route.log' 
        FIELDS TERMINATED BY ',' 
        OPTIONALLY ENCLOSED BY '"' 
        MISSING FIELD VALUES ARE NULL    
        REJECT ROWS WITH ALL NULL FIELDS        
        (   
            ID,
            PASSANGERID,
            FLIGHTID,
            PLACE,
            FLIGHT_NUMBER,
            PRICE
        )
    )    
    LOCATION ('ticket.csv','ticket_2.csv','ticket_3.csv','ticket_4.csv','ticket_5.csv','ticket_6.csv')
)
REJECT LIMIT Unlimited
NOPARALLEL;

CREATE TABLE SA_1_ORC_TICKET AS (SELECT ID, PASSANGERID AS PASSENGER_ID, FLIGHTID AS FLIGHT_ID, PRICE FROM SA_ORC_TICKET_IMP);

SELECT * FROM SA_1_ORC_TICKET;

-- SELECT * FROM SA_1_ORC_TICKET T JOIN SA_1_ORC_PASSENGER P ON T.PASSENGER_ID = P.ID JOIN SA_2_ORC_FLIGHT_SCHEDULE FS ON T.FLIGHT_ID = FS.ID;