
CREATE TABLE SA_ROUTES_IMP (
    ID INTEGER,
    DISTANCE INTEGER,
    DESTINATION_AIRCRAFT_ID INTEGER,
    ARRIVAL_AIRCRAFT_ID INTEGER
)
ORGANIZATION EXTERNAL (  
    TYPE ORACLE_LOADER    
    DEFAULT DIRECTORY imp_danych
    ACCESS PARAMETERS (       
        RECORDS DELIMITED BY NEWLINE
        BADFILE 'sa_route.bad'  
        NODISCARDFILE
        LOGFILE 'sa_route.log' 
        FIELDS TERMINATED BY ',' 
        OPTIONALLY ENCLOSED BY '"' 
        MISSING FIELD VALUES ARE NULL    
        REJECT ROWS WITH ALL NULL FIELDS        
        (   
            ID,
            DISTANCE,
            DESTINATION_AIRCRAFT_ID,
            ARRIVAL_AIRCRAFT_ID
            )
    )    
    LOCATION ('ROUTE.csv')
)
REJECT LIMIT Unlimited
NOPARALLEL;

SELECT * FROM SA_ROUTES_IMP;
CREATE TABLE SA_1_ROUTES AS (SELECT * FROM SA_ROUTES_IMP);
