 CREATE TABLE SA_AIRCRAFT_SEAT_IMPL (
    ID INTEGER,
    PLACE_ID VARCHAR(5),
    PRICE INTEGER,
    TRAVEL_CLASS VARCHAR(50),
    AIRCRAFT_ID INTEGER
)
ORGANIZATION EXTERNAL (  
    TYPE ORACLE_LOADER    
    DEFAULT DIRECTORY imp_danych
    ACCESS PARAMETERS (       
        RECORDS DELIMITED BY NEWLINE
        BADFILE 'sa_route.bad'  
        NODISCARDFILE
        LOGFILE 'sa_route.log' 
        FIELDS TERMINATED BY ',' 
        OPTIONALLY ENCLOSED BY '"' 
        MISSING FIELD VALUES ARE NULL    
        REJECT ROWS WITH ALL NULL FIELDS        
        (
            ID,
            PLACE_ID,
            PRICE,
            TRAVEL_CLASS,
            AIRCRAFT_ID
        )
    )
    LOCATION ('AIRCRAFT_SEAT.csv')
)
REJECT LIMIT Unlimited
NOPARALLEL;

CREATE TABLE SA_AIRLINE_TRANSACTION_IMPL (
    ID INTEGER,
    FLIGHT_SCHEDULE_ID INTEGER,
    PASSENGER_ID INTEGER,
    AIRCRAFT_SEAT_ID CHAR(50)
)
ORGANIZATION EXTERNAL (  
    TYPE ORACLE_LOADER    
    DEFAULT DIRECTORY imp_danych
    ACCESS PARAMETERS (       
        RECORDS DELIMITED BY NEWLINE
        BADFILE 'sa_route.bad'  
        NODISCARDFILE
        LOGFILE 'sa_route.log' 
        FIELDS TERMINATED BY ',' 
        OPTIONALLY ENCLOSED BY '"' 
        MISSING FIELD VALUES ARE NULL    
        REJECT ROWS WITH ALL NULL FIELDS        
        (
            ID,
            FLIGHT_SCHEDULE_ID,
            PASSENGER_ID,
            AIRCRAFT_SEAT_ID
        )
    )
    LOCATION ('AIRLINE_TRANSACTION.csv')
)
REJECT LIMIT Unlimited
NOPARALLEL;


CREATE TABLE SA_1_TICKET AS 
    (SELECT SATI.ID, PRICE, TRAVEL_CLASS, FLIGHT_SCHEDULE_ID, PASSENGER_ID 
    FROM SA_AIRCRAFT_SEAT_IMPL SASI 
    JOIN SA_AIRLINE_TRANSACTION_IMPL SATI ON SATI.aircraft_seat_id = SASI.id
    JOIN SA_PASSENGER_IMPL SPI ON SPI.ID = PASSENGER_ID);
    
ALTER TABLE SA_1_PASSENGER ADD CONSTRAINT PK_SA1_PASSENGER PRIMARY KEY (ID);
ALTER TABLE SA_1_FLIGHT_SCHEDULE ADD CONSTRAINT PK_SA1_FLIGHT_SCHEDULE PRIMARY KEY (ID);
ALTER TABLE SA_1_TICKET ADD CONSTRAINT PK_SA1_TICKET PRIMARY KEY (ID);
ALTER TABLE SA_1_TICKET ADD CONSTRAINT FK_SA1_TICKET_PASSENEGER FOREIGN KEY (PASSENGER_ID) REFERENCES SA_1_PASSENGER(ID);
ALTER TABLE SA_1_TICKET ADD CONSTRAINT FK_SA1_TICKET_FLIGHT_SCHEDULE FOREIGN KEY (FLIGHT_SCHEDULE_ID) REFERENCES SA_1_FLIGHT_SCHEDULE(ID);
